spring.application.name=ecommerce
spring.datasource.url=jdbc:mysql://localhost:3306/estore
spring.datasource.username=root
spring.datasource.password=yash0825
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# password change is needed
